tabPanel(title = "Housing",
         fluidPage(
           fluidRow(
             column(6,
                    br(),
                    uiOutput("housing_text")
             ),
             column(6,
                    plotOutput("")
             )
           ),
           fluidRow(
             column(6,
                    plotOutput("")
             ),
             column(6,
                    plotOutput("")
             )
           )
         ))