tabPanel(title = "Housing",
         fluidPage(
           fluidRow(
             column(6,
                    br(),
                    uiOutput("housing_text")
             ),
             column(6,
                    plotOutput("housing_size")
             )
           ),
           fluidRow(
             column(6,
                    plotOutput("housing_type")
             ),
             column(6,
                    plotOutput("housing_prices")
             )
           )
         ))